{ nsp: 
   { name: '/',
     server: 
      { nsps: [Object],
        _path: '/socket.io',
        _serveClient: true,
        _adapter: [Function: Adapter],
        _origins: '*:*',
        sockets: [Circular],
        eio: [Object],
        engine: [Object] },
     sockets: [ [Circular] ],
     connected: { x9NsBQpR7sDCbscOAAAC: [Circular] },
     fns: [ [Function] ],
     ids: 0,
     acks: {},
     adapter: { nsp: [Circular], rooms: [Object], sids: [Object], encoder: {} },
     _events: { connection: [Function] } },
  server: 
   { nsps: { '/': [Object] },
     _path: '/socket.io',
     _serveClient: true,
     _adapter: [Function: Adapter],
     _origins: '*:*',
     sockets: 
      { name: '/',
        server: [Circular],
        sockets: [Object],
        connected: [Object],
        fns: [Object],
        ids: 0,
        acks: {},
        adapter: [Object],
        _events: [Object] },
     eio: 
      { clients: [Object],
        clientsCount: 1,
        pingTimeout: 60000,
        pingInterval: 25000,
        upgradeTimeout: 10000,
        maxHttpBufferSize: 100000000,
        transports: [Object],
        allowUpgrades: true,
        allowRequest: [Function],
        cookie: 'io',
        ws: [Object],
        _events: [Object] },
     engine: 
      { clients: [Object],
        clientsCount: 1,
        pingTimeout: 60000,
        pingInterval: 25000,
        upgradeTimeout: 10000,
        maxHttpBufferSize: 100000000,
        transports: [Object],
        allowUpgrades: true,
        allowRequest: [Function],
        cookie: 'io',
        ws: [Object],
        _events: [Object] } },
  adapter: 
   { nsp: 
      { name: '/',
        server: [Object],
        sockets: [Object],
        connected: [Object],
        fns: [Object],
        ids: 0,
        acks: {},
        adapter: [Circular],
        _events: [Object] },
     rooms: 
      { vysWAiF5GaaQ783oAAAA: [],
        FXrehj4EjHyQGDWLAAAB: [],
        x9NsBQpR7sDCbscOAAAC: [Object] },
     sids: { x9NsBQpR7sDCbscOAAAC: [Object] },
     encoder: {} },
  id: 'x9NsBQpR7sDCbscOAAAC',
  client: 
   { server: 
      { nsps: [Object],
        _path: '/socket.io',
        _serveClient: true,
        _adapter: [Function: Adapter],
        _origins: '*:*',
        sockets: [Object],
        eio: [Object],
        engine: [Object] },
     conn: 
      { id: 'x9NsBQpR7sDCbscOAAAC',
        server: [Object],
        upgraded: true,
        readyState: 'open',
        writeBuffer: [],
        packetsFn: [],
        sentCallbackFn: [],
        request: [Object],
        checkIntervalTimer: null,
        upgradeTimeoutTimer: [Object],
        pingTimeoutTimer: [Object],
        transport: [Object],
        _events: [Object] },
     encoder: {},
     decoder: { reconstructor: null, _callbacks: [Object] },
     id: 'x9NsBQpR7sDCbscOAAAC',
     request: 
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: {},
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: false,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '/socket.io/?EIO=2&transport=polling&t=1432010001330-0',
        method: 'GET',
        statusCode: null,
        client: [Object],
        _consuming: true,
        _dumped: true,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        _query: [Object],
        res: [Object],
        cleanup: [Function: cleanup],
        read: [Function],
        secret: 'WednesdayNightMeatBandits',
        cookies: [Object],
        signedCookies: [Object],
        session: [Object] },
     onclose: [Function],
     ondata: [Function],
     ondecoded: [Function],
     sockets: [ [Circular] ],
     nsps: { '/': [Circular] } },
  conn: 
   { id: 'x9NsBQpR7sDCbscOAAAC',
     server: 
      { clients: [Object],
        clientsCount: 1,
        pingTimeout: 60000,
        pingInterval: 25000,
        upgradeTimeout: 10000,
        maxHttpBufferSize: 100000000,
        transports: [Object],
        allowUpgrades: true,
        allowRequest: [Function],
        cookie: 'io',
        ws: [Object],
        _events: [Object] },
     upgraded: true,
     readyState: 'open',
     writeBuffer: [],
     packetsFn: [],
     sentCallbackFn: [],
     request: 
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: {},
        _maxListeners: 10,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: false,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '/socket.io/?EIO=2&transport=polling&t=1432010001330-0',
        method: 'GET',
        statusCode: null,
        client: [Object],
        _consuming: true,
        _dumped: true,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        _query: [Object],
        res: [Object],
        cleanup: [Function: cleanup],
        read: [Function],
        secret: 'WednesdayNightMeatBandits',
        cookies: [Object],
        signedCookies: [Object],
        session: [Object] },
     checkIntervalTimer: null,
     upgradeTimeoutTimer: 
      { _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 1432010001416,
        _onTimeout: null,
        _repeat: false,
        ontimeout: null },
     pingTimeoutTimer: 
      { _idleTimeout: 85000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 1432010022172,
        _onTimeout: [Function],
        _repeat: false },
     transport: 
      { readyState: 'opening',
        socket: [Object],
        writable: true,
        supportsBinary: true,
        _events: [Object] },
     _events: { close: [Object], data: [Function] } },
  rooms: [ 'x9NsBQpR7sDCbscOAAAC' ],
  acks: {},
  connected: true,
  disconnected: false,
  handshake: 
   { headers: 
      { host: 'localhost:3000',
        connection: 'keep-alive',
        'user-agent': 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36',
        accept: '*/*',
        referer: 'http://localhost:3000/login-page',
        'accept-encoding': 'gzip, deflate, sdch',
        'accept-language': 'en-US,en;q=0.8',
        cookie: 'io=FXrehj4EjHyQGDWLAAAB; SupportAppVersion=1; connect.sid=s%3APM5_mxSUS6mEsXnmQO1RYSJUHlW8URZr.lw7itV6dAey7UT%2BLB%2Bmln7d6V%2BL%2F1cuCXyBZCkP6ywQ; user=%7B%22_id%22%3A%2254f51910462b95aa2a62c5d1%22%2C%22username%22%3A%22Katya%22%2C%22password%22%3A%22Bachata%22%2C%22__v%22%3A0%7D' },
     time: 'Tue May 19 2015 13:33:21 GMT+0900 (JST)',
     address: { address: '127.0.0.1', family: 'IPv4', port: 3000 },
     xdomain: false,
     secure: false,
     issued: 1432010001335,
     url: '/socket.io/?EIO=2&transport=polling&t=1432010001330-0',
     query: { EIO: '2', transport: 'polling', t: '1432010001330-0' } },
  _events: 
   { peopleJoinServer: [Function],
     doctorsJoinServer: [Function],
     sendMsg: [Function],
     disconnect: [Function],
     createRoom: [Function],
     joinRoom: [Function],
     check: [Function],
     chatRoomCheck: [Function],
     leaveRoom: [Function],
     removeRoom: [Function],
     getPeopleList: [Function],
     initialUpdate: [Function] } }
